### ISSUE TITLE
Stats seem to not have been updated since January 2023

### ISSUE THREAD

**Issue by corneliusroemer** [bioconda/bioconda-stats#1]
I noticed that the download stats appear to be frozen in time since January 2023, see e.g.
<img width="797" alt="image" src="https://github.com/bioconda/bioconda-stats/assets/25161793/3cc2d813-3b30-4fc5-af0c-fb97f1174c02">
https://bioconda.github.io/recipes/treetime/README.html?highlight=treetime#package-package%20&#x27;treetime&#x27;

**Comment by aliciaaevans** [comment]
Good news: bioconda-plots is now updated to use the latest data from bioconda-stats repo.
Less than good news: Updated plots are including too many past versions which clutters up the plot and the legend. I'll be looking into that next.

**Comment by aliciaaevans** [comment]
Fixed version filtering issue in https://github.com/bioconda/bioconda-plots/pull/7

**Comment by corneliusroemer** [comment]
Thank you 🎉
